"""Initial schema

Revision ID: 5fc2232c0cfd
Revises: 
Create Date: 2025-11-15 14:32:21.299369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc2232c0cfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('violation_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_violation_id'), 'audit_logs', ['violation_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diia_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_diia_user_id'), 'users', ['diia_user_id'], unique=True)
    op.create_table('violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED', 'SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='violationstatus'), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('license_plate_confidence', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('verification_time_seconds', sa.Integer(), nullable=True),
    sa.Column('evidence_package_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('police_case_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('violation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_created_at'), 'violations', ['created_at'], unique=False)
    op.create_index(op.f('ix_violations_license_plate'), 'violations', ['license_plate'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_index(op.f('ix_violations_user_id'), 'violations', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('violation_id', sa.String(length=36), nullable=False),
    sa.Column('photo_type', sa.Enum('INITIAL', 'VERIFICATION', 'CONTEXT', name='phototype'), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('ocr_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_violation_id'), 'photos', ['violation_id'], unique=False)
    op.create_table('violation_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('violation_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED', 'SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='violationstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'PENDING_VERIFICATION', 'VERIFIED', 'SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='violationstatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('change_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_status_history_changed_at'), 'violation_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_violation_status_history_violation_id'), 'violation_status_history', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_status_history_violation_id'), table_name='violation_status_history')
    op.drop_index(op.f('ix_violation_status_history_changed_at'), table_name='violation_status_history')
    op.drop_table('violation_status_history')
    op.drop_index(op.f('ix_photos_violation_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_violations_user_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_license_plate'), table_name='violations')
    op.drop_index(op.f('ix_violations_created_at'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_users_diia_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_violation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
